### ISSUE TITLE
Alternate formats for XML

### ISSUE THREAD

**Issue by aakarshsingh** [aakarshsingh/latin_text_antique_digiliblt#1]
@kylepjohnson These XMLs would need formatting right? What format are we expecting? JSON or Plain Text? Let me know, I will get on with it.

**Comment by kylepjohnson** [comment]
Thank you for offering. JSON format would be terrific. It looks pretty clean, so I think you'll be able to pretty easily. A few tips:

1)
You'll find the text's title at `head`:

```
<head>de orthographia</head>
```

Text units under `milestone`:

```
  <milestone unit="par" n="1" />
 <p> Agroecius, cum Latine scribas, per diphthongon scribendum, non, ut quidam putant, per i Agricius. </p>
```

2)
For the JSON, if possible, I would like this to be simple, as we have done for the Perseus texts:

`````` javascript
{"work": <work_title>, "meta": "section", "language": "latin", "author": <author_name>, "corpus": "perseus", "text": {"1": "Agroecius, cum Latine scribas, per diphthongon scribendum, non, ut quidam putant, per i Agricius", "2": "triceni de tricentis dices, trigeni de triginta.", ...}}```

3)
Please put the JSON in a dir called `json` and the XML in `xml`, in the root of the repo. Don't worry about the "meta" tag for now -- just call it "section" for now and I can fill that out later.

4)
The reason why JSON  is important is because it is what the website written by @lukehollis is writing. See [an API example here](http://api.cltk.org:5000/lang/latin/corpus/perseus/author/vergil/text/aeneid?chunk1=1).

5) Put the script that you use to do the transformation in the root of the repo.

Please check in within a week how this task is going. Let me know if I can help! 
``````

**Comment by aakarshsingh** [comment]
@kylepjohnson Thank you for the details about the format, I will get back to you by the end of the week with the JSON

**Comment by kylepjohnson** [comment]
Hi @aakarshsingh How are we doing on this one?

**Comment by aakarshsingh** [comment]
I was travelling for a while, I am sorry about the delay. Give me a few days.

**Comment by aakarshsingh** [comment]
@kylepjohnson - Can you help me with this file 

https://github.com/cltk/latin_text_antique_digiliblt/blob/master/corpora/dlt000001.xml

This one has no head, I think some other files also have this format. What do we do about these?

**Comment by aakarshsingh** [comment]
What do we do with supplied tags?

**Comment by kylepjohnson** [comment]
On the file you linked to: this is a nasty one. The text is called "De controuersiis agrorum" by "Agennius Vrbicus". (Note it's part of a compiled work called the "Corpus agrimensorum Romanorum"). For some reason, probably because it is unusual, there is no `head`, just title and author:

``` xml
<titleStmt>
        <title>De controuersiis agrorum</title>
        <author>Agennius Vrbicus</author>
```

Anything from the "Corpus agrimensorum" might be like this. Does this help you?

About `<supplied>` tag: These are important and I'm glad you spotted them. Yes, we do want them. They indicate that an modern scholar has made a correction to the original manuscript. So this XML here …

``` xml
<text>
    <body>
      <p><milestone unit="page" n="p. 20 Thulin"/> <gap/> … , ut ab initio quodam ad certa<supplied>m</supplied> finium dispositionem procedit et exigit ornatum, silentio transire nequeo. …
```

… would look like this in your "text" field …

```
… ut ab initio quodam ad certa<m> finium dispositionem procedit et exigit ornatum, silentio transire nequeo. …
```

So as you can see, when you see a `<supplied>` tag, you'll need to convert it to a `<` (and `</supplied>` to a `>`). Confusing, I know!

Example on the website: http://digiliblt.lett.unipmn.it/xtf/view?docId=dlt000001/dlt000001.xml;query=De%20controuersiis%20agrorum;brand=default.

**Comment by aakarshsingh** [comment]
Thanks for the update, I will factor all that in and go ahead with the script.

**Comment by kylepjohnson** [comment]
This issue has grown cold. I'm not opposed to closing it, for now, as a "wont fix". @aakarshsingh ?
